apiVersion: v1beta1
kind: Deployment
metadata:
  labels:
    app: etl-qqp
  name: etl-qqp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl-qqp
  template:
    metadata:
      labels:
        app: etl-qqp
      spec:
        containers:
        - env:
          - name: DATABASE_HOST
            value: host
          - name: DATABASE_USERNAME
            value: username
          - name: DATABASE_PASSWORD
            value: password
          - name: DATABASE_PORT
            value: '5432'
        image: mxabierto/etl-qqp:v1
      name: etl-qqp