apiVersion: v1beta1
kind: Deployment
metadata:
  labels:
    app: postgres-qqp
  name: postgres-qqp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-qqp
  template:
    metadata:
      labels:
        app: postgres-qqp
      spec:
        containers:
        - env:
          - name: DATABASE_HOST
            value: host
          - name: DATABASE_USERNAME
            value: username
          - name: DATABASE_PASSWORD
            value: password
          - name: DATABASE_PORT
            value: '5432'
        image: postgres
      name: postgres-qqp
      ports:
      - containerPort: 5432
        protocol: TCP
      volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: postgres-qqp
    volumes:
    - hostPath:
        path: /path/
      name: postgres-qqp